services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - /etc/letsencrypt/live/www.enreglaintegral.cl/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/www.enreglaintegral.cl/privkey.pem:/etc/ssl/private/privkey.pem:ro
